- name: Install httpd and php packages
  tags: apache,amazon,httpd
  package:
    name:
    - "{{ apache_package_name }}"
    - "{{ php_package_name }}"
    state: latest

- name: Start and enable httpd (Amazon)
  tags: apache,amazon,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Copy default html files for site
  tags: apache,httpd,apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644